Handle Fast_order and no-call params
BorysDrozhak/wa-tilda pull request #13
Opened 2022-08-27 15:53 UTC by alonewerwolf

Fix rounding

2022-08-27 16:11 UTC, BorysDrozhak requested changes

2022-08-27 16:11 UTC, BorysDrozhak commented on tests/unit/data/tilda_orders.py
> +answer1 = '''NO CALL
Погодь
Ти тут догіку міняєш
Народ перестане дзвонити клієнту взагалі

2022-08-27 16:13 UTC, alonewerwolf commented on tests/unit/data/tilda_orders.py
> +answer1 = '''NO CALL
це у випадку якщо приходять параметри або 
НЕдзвонити-Написати або ж no-call

2022-08-28 11:49 UTC, BorysDrozhak approved these changes

2022-08-28 11:54 UTC, merged